INSERT INTO `tb_nac_nacionalidade` VALUES(1, "Brasileiro");
INSERT INTO `tb_nac_nacionalidade` VALUES(2, "Venezuelano");
INSERT INTO `tb_nac_nacionalidade` VALUES(3, "Colombiano");
INSERT INTO `tb_nac_nacionalidade` VALUES(4, "Peruano");
INSERT INTO `tb_nac_nacionalidade` VALUES(5, "Equatoriano");
INSERT INTO `tb_nac_nacionalidade` VALUES(6, "Surinamês");
INSERT INTO `tb_nac_nacionalidade` VALUES(7, "Guianense");
INSERT INTO `tb_nac_nacionalidade` VALUES(8, "Naturalizado Brasileiro");
INSERT INTO `tb_nac_nacionalidade` VALUES(9, "Argentino");
INSERT INTO `tb_nac_nacionalidade` VALUES(10, "Boliviano");
INSERT INTO `tb_nac_nacionalidade` VALUES(11, "Chileno");
INSERT INTO `tb_nac_nacionalidade` VALUES(12, "Paraguaio");
INSERT INTO `tb_nac_nacionalidade` VALUES(13, "Uruguaio");
INSERT INTO `tb_nac_nacionalidade` VALUES(14, "Alemão");
INSERT INTO `tb_nac_nacionalidade` VALUES(15, "Belga");
INSERT INTO `tb_nac_nacionalidade` VALUES(16, "Britânico");
INSERT INTO `tb_nac_nacionalidade` VALUES(17, "Canadense");
INSERT INTO `tb_nac_nacionalidade` VALUES(18, "Espanhol");
INSERT INTO `tb_nac_nacionalidade` VALUES(19, "Norte Americano (EUA)");
INSERT INTO `tb_nac_nacionalidade` VALUES(20, "Francês");
INSERT INTO `tb_nac_nacionalidade` VALUES(21, "Suíço");
INSERT INTO `tb_nac_nacionalidade` VALUES(22, "Italiano");
INSERT INTO `tb_nac_nacionalidade` VALUES(23, "Japonês");
INSERT INTO `tb_nac_nacionalidade` VALUES(24, "Chinês");
INSERT INTO `tb_nac_nacionalidade` VALUES(25, "Coreano");
INSERT INTO `tb_nac_nacionalidade` VALUES(26, "Português");
