INSERT INTO `tb_arc_area_conhecimento` VALUES (1,'Ciências Exatas e da Terra',NULL);
INSERT INTO `tb_arc_area_conhecimento` VALUES (2,'Ciências Biológicas',NULL);
INSERT INTO `tb_arc_area_conhecimento` VALUES (3,'Engenharias',NULL);
INSERT INTO `tb_arc_area_conhecimento` VALUES (4,'Ciências da Saúde',NULL);
INSERT INTO `tb_arc_area_conhecimento` VALUES (5,'Ciências Agrárias',NULL);
INSERT INTO `tb_arc_area_conhecimento` VALUES (6,'Ciências Sociais Aplicadas',NULL);
INSERT INTO `tb_arc_area_conhecimento` VALUES (7,'Ciências Humanas',NULL);
INSERT INTO `tb_arc_area_conhecimento` VALUES (8,'Linguística, Letras e Artes',NULL);
INSERT INTO `tb_arc_area_conhecimento` VALUES (9,'Outros',NULL);
INSERT INTO `tb_arc_area_conhecimento` VALUES (10,'Matemática',1);
INSERT INTO `tb_arc_area_conhecimento` VALUES (11,'Probabilidade e Estatística',1);
INSERT INTO `tb_arc_area_conhecimento` VALUES (12,'Ciência da Computação',1);
INSERT INTO `tb_arc_area_conhecimento` VALUES (13,'Astronomia',1);
INSERT INTO `tb_arc_area_conhecimento` VALUES (14,'Física',1);
INSERT INTO `tb_arc_area_conhecimento` VALUES (15,'Química',1);
INSERT INTO `tb_arc_area_conhecimento` VALUES (16,'Geociências',1);
INSERT INTO `tb_arc_area_conhecimento` VALUES (17,'Oceanografia',1);
INSERT INTO `tb_arc_area_conhecimento` VALUES (18,'Biologia Geral',2);
INSERT INTO `tb_arc_area_conhecimento` VALUES (19,'Genética',2);
INSERT INTO `tb_arc_area_conhecimento` VALUES (20,'Botânica',2);
INSERT INTO `tb_arc_area_conhecimento` VALUES (21,'Zoologia',2);
INSERT INTO `tb_arc_area_conhecimento` VALUES (22,'Ecologia',2);
INSERT INTO `tb_arc_area_conhecimento` VALUES (23,'Morfologia',2);
INSERT INTO `tb_arc_area_conhecimento` VALUES (24,'Fisiologia',2);
INSERT INTO `tb_arc_area_conhecimento` VALUES (25,'Bioquímica',2);
INSERT INTO `tb_arc_area_conhecimento` VALUES (26,'Biofísica',2);
INSERT INTO `tb_arc_area_conhecimento` VALUES (27,'Farmacologia',2);
INSERT INTO `tb_arc_area_conhecimento` VALUES (28,'Imunologia',2);
INSERT INTO `tb_arc_area_conhecimento` VALUES (29,'Microbiologia',2);
INSERT INTO `tb_arc_area_conhecimento` VALUES (30,'Parasitologia',2);
INSERT INTO `tb_arc_area_conhecimento` VALUES (31,'Engenharia Civil',3);
INSERT INTO `tb_arc_area_conhecimento` VALUES (32,'Engenharia de Minas',3);
INSERT INTO `tb_arc_area_conhecimento` VALUES (33,'Engenharia de Materiais e Metalúrgica',3);
INSERT INTO `tb_arc_area_conhecimento` VALUES (34,'Engenharia Elétrica',3);
INSERT INTO `tb_arc_area_conhecimento` VALUES (35,'Engenharia Mecânica',3);
INSERT INTO `tb_arc_area_conhecimento` VALUES (36,'Engenharia Química',3);
INSERT INTO `tb_arc_area_conhecimento` VALUES (37,'Engenharia Sanitária',3);
INSERT INTO `tb_arc_area_conhecimento` VALUES (38,'Engenharia de Produção',3);
INSERT INTO `tb_arc_area_conhecimento` VALUES (39,'Engenharia Nuclear',3);
INSERT INTO `tb_arc_area_conhecimento` VALUES (40,'Engenharia de Transportes',3);
INSERT INTO `tb_arc_area_conhecimento` VALUES (41,'Engenharia Naval e Oceânica',3);
INSERT INTO `tb_arc_area_conhecimento` VALUES (42,'Engenharia Aeroespacial',3);
INSERT INTO `tb_arc_area_conhecimento` VALUES (43,'Engenharia Biomédica',3);
INSERT INTO `tb_arc_area_conhecimento` VALUES (44,'Medicina',4);
INSERT INTO `tb_arc_area_conhecimento` VALUES (45,'Odontologia',4);
INSERT INTO `tb_arc_area_conhecimento` VALUES (46,'Farmácia',4);
INSERT INTO `tb_arc_area_conhecimento` VALUES (47,'Enfermagem',4);
INSERT INTO `tb_arc_area_conhecimento` VALUES (48,'Nutrição',4);
INSERT INTO `tb_arc_area_conhecimento` VALUES (49,'Saúde Coletiva',4);
INSERT INTO `tb_arc_area_conhecimento` VALUES (50,'Fonoaudiologia',4);
INSERT INTO `tb_arc_area_conhecimento` VALUES (51,'Fisioterapia e Terapia Ocupacional',4);
INSERT INTO `tb_arc_area_conhecimento` VALUES (52,'Educação Física',4);
INSERT INTO `tb_arc_area_conhecimento` VALUES (53,'Agronomia',5);
INSERT INTO `tb_arc_area_conhecimento` VALUES (54,'Recursos Florestais e Engenharia Florestal',5);
INSERT INTO `tb_arc_area_conhecimento` VALUES (55,'Engenharia Agrícola',5);
INSERT INTO `tb_arc_area_conhecimento` VALUES (56,'Zootecnia',5);
INSERT INTO `tb_arc_area_conhecimento` VALUES (57,'Medicina Veterinária',5);
INSERT INTO `tb_arc_area_conhecimento` VALUES (58,'Recursos Pesqueiros e Engenharia de Pesca',5);
INSERT INTO `tb_arc_area_conhecimento` VALUES (59,'Ciência e Tecnologia de Alimentos',5);
INSERT INTO `tb_arc_area_conhecimento` VALUES (60,'Direito',6);
INSERT INTO `tb_arc_area_conhecimento` VALUES (61,'Administração',6);
INSERT INTO `tb_arc_area_conhecimento` VALUES (62,'Economia',6);
INSERT INTO `tb_arc_area_conhecimento` VALUES (63,'Arquitetura e Urbanismo',6);
INSERT INTO `tb_arc_area_conhecimento` VALUES (64,'Planejamento Urbano e Regional',6);
INSERT INTO `tb_arc_area_conhecimento` VALUES (65,'Demografia',6);
INSERT INTO `tb_arc_area_conhecimento` VALUES (66,'Ciência da Informação',6);
INSERT INTO `tb_arc_area_conhecimento` VALUES (67,'Museologia',6);
INSERT INTO `tb_arc_area_conhecimento` VALUES (68,'Comunicação',6);
INSERT INTO `tb_arc_area_conhecimento` VALUES (69,'Serviço Social',6);
INSERT INTO `tb_arc_area_conhecimento` VALUES (70,'Economia Doméstica',6);
INSERT INTO `tb_arc_area_conhecimento` VALUES (71,'Desenho Industrial',6);
INSERT INTO `tb_arc_area_conhecimento` VALUES (72,'Turismo',6);
INSERT INTO `tb_arc_area_conhecimento` VALUES (73,'Filosofia',7);
INSERT INTO `tb_arc_area_conhecimento` VALUES (74,'Sociologia',7);
INSERT INTO `tb_arc_area_conhecimento` VALUES (75,'Antropologia',7);
INSERT INTO `tb_arc_area_conhecimento` VALUES (76,'Arqueologia',7);
INSERT INTO `tb_arc_area_conhecimento` VALUES (77,'História',7);
INSERT INTO `tb_arc_area_conhecimento` VALUES (78,'Geografia',7);
INSERT INTO `tb_arc_area_conhecimento` VALUES (79,'Psicologia',7);
INSERT INTO `tb_arc_area_conhecimento` VALUES (80,'Educação',7);
INSERT INTO `tb_arc_area_conhecimento` VALUES (81,'Ciência Política',7);
INSERT INTO `tb_arc_area_conhecimento` VALUES (82,'Teologia',7);
INSERT INTO `tb_arc_area_conhecimento` VALUES (83,'Linguística',8);
INSERT INTO `tb_arc_area_conhecimento` VALUES (84,'Letras',8);
INSERT INTO `tb_arc_area_conhecimento` VALUES (85,'Artes',8);
INSERT INTO `tb_arc_area_conhecimento` VALUES (86,'Administração Hospitalar',9);
INSERT INTO `tb_arc_area_conhecimento` VALUES (87,'Administração Rural',9);
INSERT INTO `tb_arc_area_conhecimento` VALUES (88,'Carreira Militar',9);
INSERT INTO `tb_arc_area_conhecimento` VALUES (89,'Carreira Religiosa',9);
INSERT INTO `tb_arc_area_conhecimento` VALUES (90,'Ciências',9);
INSERT INTO `tb_arc_area_conhecimento` VALUES (91,'Biomedicina',9);
INSERT INTO `tb_arc_area_conhecimento` VALUES (92,'Ciências Atuariais',9);
INSERT INTO `tb_arc_area_conhecimento` VALUES (93,'Ciências Sociais',9);
INSERT INTO `tb_arc_area_conhecimento` VALUES (94,'Decoração',9);
INSERT INTO `tb_arc_area_conhecimento` VALUES (95,'Desenho de Moda',9);
INSERT INTO `tb_arc_area_conhecimento` VALUES (96,'Desenho de Projetos',9);
INSERT INTO `tb_arc_area_conhecimento` VALUES (97,'Diplomacia',9);
INSERT INTO `tb_arc_area_conhecimento` VALUES (98,'Engenharia de Agrimensura',9);
INSERT INTO `tb_arc_area_conhecimento` VALUES (99,'Engenharia Cartográfica',9);
INSERT INTO `tb_arc_area_conhecimento` VALUES (100,'Engenharia de Armamentos',9);
INSERT INTO `tb_arc_area_conhecimento` VALUES (101,'Engenharia Mecatrônica',9);
INSERT INTO `tb_arc_area_conhecimento` VALUES (102,'Engenharia Têxtil',9);
INSERT INTO `tb_arc_area_conhecimento` VALUES (103,'Estudos Sociais',9);
INSERT INTO `tb_arc_area_conhecimento` VALUES (104,'História Natural',9);
INSERT INTO `tb_arc_area_conhecimento` VALUES (105,'Química Industrial',9);
INSERT INTO `tb_arc_area_conhecimento` VALUES (106,'Relações Internacionais',9);
INSERT INTO `tb_arc_area_conhecimento` VALUES (107,'Relações Públicas',9);
INSERT INTO `tb_arc_area_conhecimento` VALUES (108,'Secretariado Executivo',9);
INSERT INTO `tb_arc_area_conhecimento` VALUES (109,'Ensino à Distância',9);
INSERT INTO `tb_arc_area_conhecimento` VALUES (110,'Pedagogia',7);