-- MySQL Script generated by MySQL Workbench
-- Sex 14 Nov 2014 16:16:50 BRST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema selecaoneaad
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema baseCEP
-- -----------------------------------------------------

-- -----------------------------------------------------
-- procedure sp_end_endereco_insert
-- -----------------------------------------------------

DELIMITER $$
CREATE PROCEDURE sp_end_endereco_insert(v_dsEndereco VARCHAR(100), v_nmLogradouro VARCHAR(100), v_nrNumero VARCHAR(20), v_nmBairro VARCHAR(50)
,v_nmCidade VARCHAR(100), v_idCidade INT(4), v_idUf CHAR(2), v_nrCep VARCHAR(8), v_dsComplemento VARCHAR(250))
BEGIN
IF (v_IdCidade IS NULL) THEN
select CID_ID_CIDADE INTO v_idCidade FROM TB_CID_CIDADE WHERE CID_ID_UF like v_idUf
and CID_NM_CIDADE like v_nmCidade;
END IF; 
INSERT INTO tb_end_endereco(END_DS_ENDERECO,END_NM_LOGRADOURO,END_NR_NUMERO,END_NM_BAIRRO,CID_ID_CIDADE,EST_ID_UF,END_NR_CEP,END_DS_COMPLEMENTO)
VALUES (v_dsEndereco,v_nmLogradouro,v_nrNumero,v_nmBairro,v_idCidade,v_idUf,v_nrCep,v_dsComplemento);
END;$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_end_endereco_update
-- -----------------------------------------------------

DELIMITER $$
CREATE PROCEDURE sp_end_endereco_update(v_idEndereco INT(10),v_dsEndereco VARCHAR(100), v_nmLogradouro VARCHAR(100), v_nrNumero VARCHAR(20), v_nmBairro VARCHAR(50)
,v_nmCidade VARCHAR(100), v_idCidade INT(4), v_idUf CHAR(2), v_nrCep VARCHAR(8), v_dsComplemento VARCHAR(250))
BEGIN
IF (v_IdCidade IS NULL) THEN
select CID_ID_CIDADE INTO v_idCidade FROM TB_CID_CIDADE WHERE CID_ID_UF like v_idUf
and CID_NM_CIDADE like v_nmCidade;
END IF; 
UPDATE tb_end_endereco
SET END_DS_ENDERECO = v_dsEndereco,
END_NM_LOGRADOURO = v_nmLogradouro,
END_NR_NUMERO = v_nrNumero,
END_NM_BAIRRO = v_nmBairro,
CID_ID_CIDADE = v_idCidade,
EST_ID_UF = v_idUf,
END_NR_CEP = v_nrCep,
END_DS_COMPLEMENTO = v_dsComplemento
WHERE END_ID_ENDERECO = v_idEndereco;
END;$$

DELIMITER ;

-- -----------------------------------------------------
-- function fc_capitalize
-- -----------------------------------------------------

DELIMITER $$
CREATE FUNCTION fc_capitalize (input VARCHAR(255))

RETURNS VARCHAR(255)

DETERMINISTIC

BEGIN
	DECLARE len INT;
	DECLARE i INT;

	SET len   = CHAR_LENGTH(input);
	SET input = LOWER(input);
	SET i = 0;

	WHILE (i < len) DO
		IF (MID(input,i,1) = ' ' OR i = 0) THEN
			IF (i < len) THEN
				SET input = CONCAT(
					LEFT(input,i),
					UPPER(MID(input,i + 1,1)),
					RIGHT(input,len - i - 1)
				);
			END IF;
		END IF;
		SET i = i + 1;
	END WHILE;

	RETURN input;
END;$$

DELIMITER ;

-- -----------------------------------------------------
-- function fc_calcula_hash_usuario
-- -----------------------------------------------------

DELIMITER $$
CREATE FUNCTION `fc_calcula_hash_usuario` (dsNome VARCHAR(100), dsEmail VARCHAR(100), dsSenha VARCHAR(32), tpVinculoUfes CHAR(1), stSituacao CHAR(1))

RETURNS VARCHAR(32)

NOT DETERMINISTIC

BEGIN
DECLARE md5Usuario VARCHAR(32);
	SELECT 
    MD5(CONCAT(dsNome,
                    dsEmail,
                    dsSenha,
                    tpVinculoUfes,
                    stSituacao))
INTO md5Usuario;
return md5Usuario;

END;$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
